config/routes.rb
require 'sidekiq/web'
require 'users_constraint'
require 'departments_constraint'
require 'themed_campaigns_constraint'

# Sobrescrevendo a classe para poder reutilizar o método .domain
class ActionDispatch::Routing::Mapper
  def domain(request)
    request.protocol + request.domain + (request.port.nil? ? '' : ":#{request.port}")
  end

  def current_domain(request)
    request.domain + (request.port.nil? ? '' : ":#{request.port}")
  end
end

Rails.application.routes.draw do

  # devise_for :admins

  if Rails.env.production?
    # Redirecionar .com para .com.br
    constraints(host: "clictem.com") do
      match "/(*path)" => redirect {|params, req|

        if req.subdomains(0).first.present? and
           req.subdomains(0).first != "www" and
           req.subdomains(0).first != "clictem" and
           req.subdomains(0).first != "lvh"
          subdomain = "#{req.subdomains(0).first}."
        else
          subdomain = ''
        end

        "http://#{subdomain}clictem.com.br/#{params[:path]}"},  via: [:get, :post]
    end
  end


  # Redirecionar www para non-www somente se for algum subdominio
  constraints(host: /www.(?!cdlxanxere|cdlxaxim|clictem|xanxeretem)/i) do
    match "/(*path)" => redirect {|params, req|

      if req.subdomains(0).first.present? and
         req.subdomains(0).first != "www" and
         DOMAINS.include?(req.subdomains(0).first) == false
        subdomain = "#{req.subdomains(0).first}."

      elsif req.subdomains(0).first == 'www' and
            DOMAINS.include?(req.subdomains(0)[1].first) == false
        subdomain = "#{req.subdomains(0)[1]}."

      else
        subdomain = ''
      end

      "http://#{subdomain}#{current_domain(req)}/#{params[:path]}"},  via: [:get, :post]
  end


  namespace :site do
    get 'visits/new'
    get 'brands', to: 'brands#index', as: :brands
    resources :comments
  end



  devise_for :users, :path => '',
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },
    :path_names => {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'cadastre-se',
      confirmation: "confirme-seu-email",
      password: "alterar-senha"
    }




  # mount MailPreview => 'mail_view' if Rails.env.development?
  # mount RailsAdmin::Engine => '/manager-admin', as: 'rails_admin'


  # mount RedactorRails::Engine => '/redactor_rails'
  mount Sidekiq::Web, at: '/sidekiq-monitor'
  # mount UserImpersonate::Engine => "/impersonate", as: "impersonate_engine"
  get "/404", :to => "errors#not_found", as: :error_404
  get "/422", :to => "errors#unacceptable", as: :error_422
  get "/500", :to => "errors#internal_error", as: :error_500

  # config/routes.rb
  get 'switch_user' => 'switch_user#set_current_user'



  # Manager
  namespace :manager do
    get '/', to: 'users#associados', as: 'dashboard'

    resources :pages
    get '/users/clients', to: 'users#clients', as: :user_clients
    get '/users/associados', to: 'users#associados', as: :user_associados
    get '/users/prospection', to: 'users#prospection', as: :user_prospection
    resources :users
    resources :banners
    resources :banner_types
    resources :cupoms
    resources :themed_campaigns
    resources :orders
    resources :bills
    match "/change_password/:id" => "users#change_password", as: :change_password, via: :all

    namespace :ad do
      resources :departments
      resources :categories
      resources :brands
      resources :sub_categories
      resources :products
    end

    namespace :blog do
      resources :posts
      resources :authors
    end

    namespace :sms do
      resources :buys
      resources :campaigns
      resources :reports
      match 'contacts-import', to: 'contacts#import', as: :contacts_import, via: [:get, :post]
    end
  end



  namespace :api, defaults: {format: :json} do
    get 'departments', to: 'departments#index', as: :departments
    resources :products
    devise_scope :user do
      resource :session, only: [:create, :destroy]
    end
  end


  scope 'minha-conta' do

    get '/' => 'site/usuarios#resumo', as: :site_minha_conta
    get '/anuncios' => 'site/usuarios#anuncios', as: :site_anuncios

    # Rotas temporárias
    match "/usuarios/:action" => "site/usuarios#:action", as: :site_usuarios, via: :all
    match "/produto/:action" => "site/produto#:action", as: :site_produtos, via: :all
    match "/download-cupons/:id" => "site/produto#download_cupons", as: :site_download_cupons, via: :all
    match "/atrair/:action" => "site/atrair#:action", as: :site_atrair, via: :all
    match "/analisar/:action" => "site/analisar#:action", as: :site_analisar, via: :all

    get 'customers-group-count', to: 'customers#count', as: :customers_count
    get 'customers-xls', to: 'customers#export_excel', as: :customers_xls

    namespace :sms do
      resources :campaigns, path: 'campanhas'
      resources :buys, path: 'contratar'
      get 'index', as: :index
      put 'sms-update-user', to: 'buys#update_user', as: :update_user
      match 'aniversario', to: 'campaigns#birthday', as: :birthday, via: [:get, :put]
    end
    resources :groups, path: 'grupos'
    resources :customers, path: 'clientes'

    # Campanhas promocionais
    namespace :offers, path: 'ofertas' do
      resources :campaigns, path: 'campanhas'
    end

  end


  # Rotas Institucionais
  get "/sobre" => "site/page#sobre", as: :page_sobre
  get "/atendimento" => "site/page#atendimento", as: :page_atendimento
  get "/como-anunciar" => "site/page#como_anunciar", as: :page_como_anunciar
  get "/politica-de-privacidade" => "site/page#politica", as: :page_politica
  get "/termos-e-condicoes-de-uso" => "site/page#termos", as: :page_termos
  get "/produtos-e-servicos-ilegais" => "site/page#ilegais", as: :page_ilegais
  get "/acesso" => "site/page#acesso", as: :page_acesso
  get "/planos" => "site/page#planos", as: :page_planos
  match "/altera_plano" => "site/page#altera_plano", as: :page_altera_plano, via: :all
  get "/downloads" => "site/page#downloads", as: :page_downloads
  get "/links" => "site/page#links", as: :page_links
  get "/servicos" => "site/page#servicos", as: :page_servicos
  get "/spc/:cidade" => "site/page#spc", as: :page_spc



  # Blog
  # get '/post/:id', to: 'site/blog#show', as: :blog_post
  # get '/blog/:id', to: 'site/blog#index', as: :blog_posts

  # /blog/
  get '/blog', to: 'site/blog#authors', as: :blog
  # /blog/o-nome-do-blog
  get '/blog/:slug_blog', to: 'site/blog#index', as: :blog_author
  # /blog/conteudo/o-titulo-do-post
  get '/blog/conteudo/:slug_post', to: 'site/blog#show', as: :blog_post



  get "/busca" => "site/products#search", as: :site_search
  match "/send-interest" => "site/products#send_interest", as: :send_interest, via: :all
  get "/show-user-info" => "site/products#show_user_info", as: :show_user_info
  get "/produto-nao-encontrado" => "site/products#not_found", as: :product_not_found

  # enviar info do usuário
  get "/show-user-phone/:user_id/(:product_id)" => "site/products#show_user_phone", as: :show_user_phone, format: :json
  # post "/send-track"
  # psot ""

  get "sitemap" => "site/page#sitemap"


  get "/u/:user", to: redirect {|params, req|  "http://#{params[:user]}.#{req.host_with_port}" }#, :status => :moved_permanently

  # Contratação de plano
  match "/contratar" => "site/contratar#planos", as: :contratar_planos, via: :all
  match "/contratar-banners" => "site/contratar#banners", as: :contratar_banners, via: :all
  match "/contratar-dados" => "site/contratar#dados", as: :contratar_dados, via: :all


  resource :inbox, controller: 'inbox' , only: [:show,:create]



  # Rota de Departamentos com subdominio
  constraints DepartmentsConstraint do
    get '/', to: redirect {|params, req| "#{domain(req)}/#{req.subdomain}"}
    get "/:category", to: "site/products#index"
    # get "/servicos", to: "site/products#services", as: :services
    # get "/servico/:category/:product", to: "site/products#show", as: :service
  end

  # Rota para página temática
  constraints ThemedCampaignsConstraint  do
    get "/", to: "site/themed_campaigns#index", as: :themed_campaign
    post "/participar", to: "site/themed_campaigns#create", as: :themed_campaign_create
    get "/participar", to: "site/themed_campaigns#new", as: :themed_campaign_new
  end

  # Rota para lista de produtos do usuário
  constraints UsersConstraint  do
    get "/", to: "site/usuarios#produtos", as: :user_produtos
    get "/:category/:product", to: redirect {|params, req|  "#{domain(req)}/#{req.subdomain}/anuncio/#{params[:category]}/#{params[:product]}" }
  end

  root to: "site/home#index"



  # Ofertas
  get '/ofertas', to: "site/products#offers", as: :ofertas
  get '/cupons', to: "site/products#cupoms", as: :cupons



  # Rota de Departamentos com path
  scope ":department" do
    get '/(:servicos)', to: "site/products#index", as: :department
    get "/categoria/:category/(:servicos)", to: "site/products#index", as: :category
    get "/anuncio/:category/:product", to: "site/products#show", as: :ad
  end




  # get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/manager/ad.rb
module Manager::Ad
  def self.table_name_prefix
    'manager_ad_'
  end
end

app/models/manager/ad/brand.rb
class Manager::Ad::Brand < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders, :history]

  include PgSearch
  pg_search_scope :search, against: [:name],
                  ignoring: :accents,
                  using: { tsearch: { prefix: true, dictionary: "portuguese"} }

  # has_and_belongs_to_many :departments
  has_many :brands_departments
  has_many :departments, through: :brands_departments

  has_many :products

  validates :name, presence: true
end

app/models/manager/ad/brands_department.rb
class Manager::Ad::BrandsDepartment < ActiveRecord::Base
  belongs_to :brand
  belongs_to :department
end

app/models/manager/ad/campaign.rb
class Manager::Ad::Campaign < ActiveRecord::Base
  belongs_to :user
  belongs_to :themed_campaign
  belongs_to :product

  before_save do
    self.user_id = self.product.user_id
  end


end

app/models/manager/ad/category.rb
class Manager::Ad::Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders, :history]

  belongs_to :department
  has_many :products, dependent: :restrict_with_exception

  default_scope { order([:raw_order, :name]) }

  scope :on_menu, -> { where(on_menu: true).where('products_count > 0') }

  def slug_candidates
    [
      :name,
      [:name, :id]
    ]
  end

  def url
    "#{department.slug}/categoria/#{slug}"
  end
end

app/models/manager/ad/cupom.rb
class Manager::Ad::Cupom < ActiveRecord::Base
  belongs_to :user
  belongs_to :product, -> { with_deleted }
  belongs_to :seller, class_name: User
  belongs_to :offer

  validates :user, uniqueness: { scope: :product_id }

  after_create :set_info

  # Cupons válidos
  scope :valid, -> { where('due >= ? or due is null', Date.today) }

  # Emitidos nos últimos 30 dias
  scope :last_month, -> { where(created_at: ((Time.now - 30.days)..Time.now)) }

  usar_como_dinheiro :price, :offer_price

  include PgSearch
  pg_search_scope :search, against: [:code],
                  :associated_against => {
                    :user => [:name],
                    :product => [:name]
                  },
                  ignoring: :accents,
                  using: { tsearch: { prefix: true} }

  delegate :fullname, to: :user, prefix: true, allow_nil: true
  delegate :fullname, to: :seller, prefix: true, allow_nil: true
  delegate :name, to: :product, prefix: true, allow_nil: true


  # Verifica se cupom é válido
  def is_valid?
    if self.due
      self.due >= Date.today and self.used? == false
    else
      true
    end
  end


  # Total de cupons emitidos em um período
  def self.total_cupons(user, date1, date2)
    Manager::Ad::Cupom.where(seller_id: user.id, created_at: (date1.beginning_of_day..date2.end_of_day)).count
  end


  protected

  def set_info
    self.price       = self.product.price
    self.offer_price = self.product.offer_price
    self.code        = Digest::SHA1.hexdigest("#{self.id}#{Time.zone.now.to_s}")[8..16]
    self.save
  end
end

app/models/manager/ad/department.rb
class Manager::Ad::Department < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders, :history]

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  # has_and_belongs_to_many :brands
  has_many :brands_departments
  has_many :brands, through: :brands_departments

  has_many :categories, dependent: :restrict_with_exception
  has_many :products, dependent: :restrict_with_exception
  has_and_belongs_to_many :users, class_name: 'User'
  has_and_belongs_to_many :users_premium, class_name: 'User', join_table: 'departments_users_premium'
  has_many :posts, class_name: ::Blog::Post

  default_scope { order('manager_ad_departments.raw_order ASC, manager_ad_departments.name') }

  usar_como_dinheiro :banner_value

  scope :on_menu, -> {
    includes(:categories)
    .where("manager_ad_categories.on_menu = true")
    .references(:categories)
    .where(on_menu: true)
    .limit(8)
  }

  scope :with_products, -> { where("manager_ad_categories.products_count > 0") }
  scope :home, -> { where(is_home: true) }
  # Retorna um hash com os departamentos mais visualizados
  def self.most_view(date1, date2)
    date1       = date1.beginning_of_day
    date2       = date2.end_of_day
    deps        = []
    days_offset = 0

    while deps.size < 4 and days_offset <= 60 do
      ids = Visit.where(created_at: ((date1 - days_offset.days)..date2))
              .where(ad_deleted: false).select(:department_id)
              .group(:department_id)
              .order(count: :desc)
              .count

      ids.each do |id|
        if id[0]
          deps << Manager::Ad::Department.find(id[0])
        end
      end

      days_offset += 30
    end
    deps
  end

  # retorna os deptos
  def self.on_menu_cached
    Rails.cache.fetch("departments_on_menu", :expires_in => 7.days) do
      Manager::Ad::Department.on_menu
    end
  end

  def slug_candidates
    [
      :name,
      [:name, :id]
    ]
  end

end

app/models/manager/ad/image.rb
class Manager::Ad::Image < ActiveRecord::Base
  belongs_to :product

  mount_base64_uploader :file, ProductUploader

  default_scope { order(:id) }
end

app/models/manager/ad/image_temp.rb
class Manager::Ad::ImageTemp < ActiveRecord::Base
end

app/models/manager/ad/info_click.rb
class Manager::Ad::InfoClick < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  # Total de cliques em ver telefone em um período
  def self.total_clicks(user, date1, date2)
    Manager::Ad::InfoClick.where(seller_id: user.id, created_at: (date1.beginning_of_day..date2.end_of_day)).count
  end
end

app/models/manager/ad/interest.rb
class Manager::Ad::Interest < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  default_scope -> { order(created_at: :desc) }
end

app/models/manager/ad/offer.rb
class Manager::Ad::Offer < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  belongs_to :offer_campaign, class_name: Manager::Ad::OfferCampaign

  has_many :cupoms

  scope :all_offers, -> { where('date_start <= :date and date_end >= :date', date: Date.today) }

  default_scope { order(:id) }

  usar_como_dinheiro :price

  # Total de ofertas criadas em um período
  def self.total_offers(user, date1, date2)
    Manager::Ad::Offer.where(user_id: user.id)
      .where('date_start <= :date1 and date_end >= :date2',
        date1: date1.beginning_of_day, date2: date2.end_of_day).count
  end
end

app/models/manager/ad/sub_category.rb
class Manager::Ad::SubCategory < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders, :history]

  belongs_to :category
  has_many :products

  default_scope { order('raw_order ASC, name') }

  scope :on_menu, -> { where(on_menu: true).limit(5) }

  validates :category_id, presence: true

  def slug_candidates
    [
      :name,
      [:name, :id]
    ]
  end
end

app/controllers/manager/ad/brands_controller.rb
class Manager::Ad::BrandsController < Manager::ManagerController
  inherit_resources

  def index
    @brands = Manager::Ad::Brand.all
  end

  def new
    @brand = Manager::Ad::Brand.new
    @brand.name = params[:name] if params[:name]
    @brand.departments << Manager::Ad::Department.find(params[:dept]) if params[:dept]
  end


  def create
    create!(notice: "Marca adicionada!") {

      if !params[:product_id].blank?
        product = Manager::Ad::Product.find(params[:product_id])
        product.brand_id = @brand.id
        product.save
      end

      new_manager_ad_brand_path
    }
  end

  def update
    update!(notice: "Marca atualizada!") { manager_ad_brands_path }
  end

  def permitted_params
    params.permit(manager_ad_brand: [:name, :keywords, :description, :department_ids => []])
  end
end

app/controllers/manager/ad/categories_controller.rb
class Manager::Ad::CategoriesController < Manager::ManagerController
  inherit_resources

  def index
    @departments = Manager::Ad::Department.includes(:categories).all
  end

  def new
    @department = Manager::Ad::Department.find(params[:dept])
    @category = Manager::Ad::Category.new(department: @department)
  end

  def edit
    edit!{@department = @category.department}
  end

  def create
    create!(notice: "Categoria adicionada!") { new_manager_ad_category_path(dept: @category.department_id) }
  end

  def update
    update!(notice: "Categoria atualizada!") { manager_ad_categories_path }
  end

  def permitted_params
    params.permit(manager_ad_category: [:name, :department_id, :parent_id, :on_menu, :keywords, :description, :raw_order])
  end

end

app/views/manager/users/_campaign_fields.html.erb
<div class="col-md-2">
	<%= f.hidden_field :user_id, value: @user.id %>
	<%= f.input :product_id %>
</div>

app/views/manager/users/associados.html.erb
<div class="page page-table">
    <div class="panel panel-default">
        <div class="panel-heading">
          <div class="pull-right">
            <%= link_to "+ Adicionar", new_manager_user_path, class: 'btn btn-xs btn-success pull-right' %>
              <%= form_tag manager_user_associados_path, method: :get do %>
                  <%= hidden_field_tag :format, 'xls' %>
                  <button type="submit" class="btn btn-xs btn-primary">Baixar Excel</button>
              <% end %>
          </div>



            <strong><span class="fa fa-th"></span> ASSOCIADOS </strong>  - há um total de <%= @users.total_count %> ASSOCIADOS cadastrados <br>

            <%= form_tag manager_user_associados_path, method:'GET' do %>
                <%= text_field_tag :search, '', size: 70, placeholder: "Buscar usuário ou empresa" %>
            <% end %>
        </div>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <!-- <th>#</th> -->
                    <th>Criado em</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Plano</th>
                    <th>Final de contrato</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                    <!-- <td><%#= user.id %></td> -->
                    <td><%= l(user.created_at, format: :short ) %></td>
                    <% the_name = user.kind == 'pf' ? "#{user.name} #{user.last_name}" : user.name %>
                    <td>
                      <%= link_to "#{user.id}##{the_name}", edit_manager_user_path(user) %>
                      <% if user.cancel? %>
                        <span class="badge badge-danger"> Cancelado dia <%= l user.cancel_date %></span>
                      <% end %>
                    </td>
                    <td><%= user.email %></td>
                    <td><%= user.plan %></td>
                    <td>
                        <% if user.satisfaction == false %>
                            <strong class="text-danger" tooltip-append-to-body="true" tooltip-placement="top" tooltip="Cliente insatisfeito">
                                <i class="fa fa-frown-o"></i>
                            </strong>
                        <% else %>
                            <strong class="text-success" tooltip-append-to-body="true" tooltip-placement="top" tooltip="Cliente satisfeito">
                                <i class="fa fa-smile-o"></i>
                            </strong>
                        <% end %>

                        <%= l(user.contract_end, format: :short) if user.contract_end %>
                    </td>
                    <td>
                        <%= link_to user_produtos_url(subdomain: user.subdomain), target: '_blank' do %>
                            <i class="fa fa-external-link"></i> Ver Página
                        <% end %> <br />
                        <a href="<%= edit_manager_user_path(user) %>" tooltip-append-to-body="true" tooltip-placement="top" tooltip="Editar"><i class="fa fa-pencil-square-o"></i> Editar </a> <br />
                        <a href="<%= manager_change_password_path(user) %>" tooltip-append-to-body="true" tooltip-placement="top" tooltip="Trocar senha"><i class="fa fa-unlock-alt"></i> Senha </a> <br />
                        <%= link_to manager_user_path(user), method: :delete, data: { confirm: "Deseja mesmo EXCLUIR o usuário #{ user.name }?"} do %>
                            <i class="fa fa-trash-o"></i> Excluir
                        <% end %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<div class="col-md-12">
    <%= paginate @users %>
</div>

app/views/manager/users/clients.html.erb
<div class="page page-table">
    <div class="panel panel-default">
        <div class="panel-heading">
          <div class="pull-right">
            <%= link_to "+ Adicionar", new_manager_user_path, class: 'btn btn-xs btn-success pull-right' %>
              <%= form_tag manager_user_clients_path, method: :get do %>
                  <%= hidden_field_tag :format, 'xls' %>
                  <button type="submit" class="btn btn-xs btn-primary">Baixar Excel</button>
              <% end %>
          </div>



            <strong><span class="fa fa-th"></span> CLIENTES </strong>  - há um total de <%= @users.total_count %> CLIENTES cadastrados <br>

            <%= form_tag manager_user_clients_path, method:'GET' do %>
                <%= text_field_tag :search, '', size: 70, placeholder: "Buscar usuário ou empresa" %>
            <% end %>
        </div>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <!-- <th>#</th> -->
                    <th>Criado em</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Plano</th>
                    <th>Final de contrato</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                    <!-- <td><%#= user.id %></td> -->
                    <td><%= l(user.created_at, format: :short ) %></td>
                    <% the_name = user.kind == 'pf' ? "#{user.name} #{user.last_name}" : user.name %>
                    <td>
                      <%= link_to "#{user.id}##{the_name}", edit_manager_user_path(user) %>
                      <% if user.cancel? %>
                        <span class="badge badge-danger"> Cancelado dia <%= l user.cancel_date %></span>
                      <% end %>
                    </td>
                    <td><%= user.email %></td>
                    <td><%= user.plan %></td>
                    <td>
                        <% if user.satisfaction == false %>
                            <strong class="text-danger" tooltip-append-to-body="true" tooltip-placement="top" tooltip="Cliente insatisfeito">
                                <i class="fa fa-frown-o"></i>
                            </strong>
                        <% else %>
                            <strong class="text-success" tooltip-append-to-body="true" tooltip-placement="top" tooltip="Cliente satisfeito">
                                <i class="fa fa-smile-o"></i>
                            </strong>
                        <% end %>

                        <%= l(user.contract_end, format: :short) if user.contract_end %>
                    </td>
                    <td>
                        <%= link_to user_produtos_url(subdomain: user.subdomain), target: '_blank' do %>
                            <i class="fa fa-external-link"></i> Ver Página
                        <% end %> <br />
                        <a href="<%= edit_manager_user_path(user) %>" tooltip-append-to-body="true" tooltip-placement="top" tooltip="Editar"><i class="fa fa-pencil-square-o"></i> Editar </a> <br />
                        <a href="<%= manager_change_password_path(user) %>" tooltip-append-to-body="true" tooltip-placement="top" tooltip="Trocar senha"><i class="fa fa-unlock-alt"></i> Senha </a> <br />
                        <%= link_to manager_user_path(user), method: :delete, data: { confirm: "Deseja mesmo EXCLUIR o usuário #{ user.name }?"} do %>
                            <i class="fa fa-trash-o"></i> Excluir
                        <% end %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<div class="col-md-12">
    <%= paginate @users %>
</div>

app/views/manager/users/edit.html.erb
<section class="page-form-ele page">
  <section class="panel panel-default">
      <div class="panel-heading"><strong><span class="fa fa-th"></span> Editando Usuário</strong> - <%= @user.id %>#<%= @user.name %></div>
      <div class="panel-body">

        <%= simple_form_for @user, url: manager_user_path, html: { method: :put, novalidate: true } do |f| %>
            <%= render 'form', f: f  %>
        <% end %>
      </div>
  </section>
</section>

app/views/manager/users/index.html.erb
<div class="page page-table">
    <div class="panel panel-default">
        <div class="panel-heading">
          <div class="pull-right">
            <%= link_to "+ Adicionar", new_manager_user_path, class: 'btn btn-xs btn-success pull-right' %>
              <%= form_tag manager_users_path, method: :get do %>
                  <%= hidden_field_tag :format, 'xls' %>
                  <button type="submit" class="btn btn-xs btn-primary">Baixar Excel</button>
              <% end %>
          </div>

            <strong><span class="fa fa-th"></span> Usuários / Empresas </strong>  - há um total de <%= @users.total_count %> usuários cadastrados <br>

            <%= form_tag manager_users_path, method:'GET' do %>
                <%= text_field_tag :search, '', size: 70, placeholder: "Buscar usuário ou empresa" %>
            <% end %>


        </div>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <!-- <th>#</th> -->
                    <th>Criado em</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Anúncios</th>
                    <th>Qtde Acessos</th>
                    <th>Último Login em</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                    <!-- <td><%#= user.id %></td> -->
                    <td><%= l(user.created_at, format: :short ) %></td>
                    <% the_name = user.kind == 'pf' ? "#{user.name} #{user.last_name}" : user.name %>
                    <td>
                        <%= link_to "#{user.id}##{the_name}", edit_manager_user_path(user) %> <br />
                        <small><%= user.label_plan %></small>
                        <% if user.cancel? %>
                          <span class="badge badge-danger"> Cancelado dia <%= l user.cancel_date %></span>
                        <% end %>
                    </td>
                    <td><%= user.email %></td>
                    <td><%= user.products.size %></td>
                    <td><%= user.sign_in_count %></td>
                    <td><%= l(user.last_sign_in_at, format: :short) if user.last_sign_in_at %></td>
                    <td nowrap>
                        <a href="<%= edit_manager_user_path(user) %>" tooltip-append-to-body="true" tooltip-placement="top" tooltip="Editar"><i class="fa fa-pencil-square-o"></i> Editar</a> <br />
                        <%= link_to manager_change_password_path(user) do %>
                            <i class="fa fa-unlock-alt"></i> Senha
                        <% end %><br />
                        <%= link_to manager_user_path(user), method: :delete, data: { confirm: "Deseja mesmo EXCLUIR o usuário #{user.name}?" } do %>
                            <i class="fa fa-trash-o"></i> Excluir
                        <% end %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<div class="col-md-12">
    <%= paginate @users %>
</div>