config/routes.rb
require 'sidekiq/web'
require 'users_constraint'
require 'departments_constraint'
require 'themed_campaigns_constraint'

# Sobrescrevendo a classe para poder reutilizar o método .domain
class ActionDispatch::Routing::Mapper
  def domain(request)
    request.protocol + request.domain + (request.port.nil? ? '' : ":#{request.port}")
  end

  def current_domain(request)
    request.domain + (request.port.nil? ? '' : ":#{request.port}")
  end
end

Rails.application.routes.draw do

  # devise_for :admins

  if Rails.env.production?
    # Redirecionar .com para .com.br
    constraints(host: "clictem.com") do
      match "/(*path)" => redirect {|params, req|

        if req.subdomains(0).first.present? and
           req.subdomains(0).first != "www" and
           req.subdomains(0).first != "clictem" and
           req.subdomains(0).first != "lvh"
          subdomain = "#{req.subdomains(0).first}."
        else
          subdomain = ''
        end

        "http://#{subdomain}clictem.com.br/#{params[:path]}"},  via: [:get, :post]
    end
  end


  # Redirecionar www para non-www somente se for algum subdominio
  constraints(host: /www.(?!cdlxanxere|cdlxaxim|clictem|xanxeretem)/i) do
    match "/(*path)" => redirect {|params, req|

      if req.subdomains(0).first.present? and
         req.subdomains(0).first != "www" and
         DOMAINS.include?(req.subdomains(0).first) == false
        subdomain = "#{req.subdomains(0).first}."

      elsif req.subdomains(0).first == 'www' and
            DOMAINS.include?(req.subdomains(0)[1].first) == false
        subdomain = "#{req.subdomains(0)[1]}."

      else
        subdomain = ''
      end

      "http://#{subdomain}#{current_domain(req)}/#{params[:path]}"},  via: [:get, :post]
  end


  namespace :site do
    get 'visits/new'
    get 'brands', to: 'brands#index', as: :brands
    resources :comments
  end



  devise_for :users, :path => '',
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },
    :path_names => {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'cadastre-se',
      confirmation: "confirme-seu-email",
      password: "alterar-senha"
    }




  # mount MailPreview => 'mail_view' if Rails.env.development?
  # mount RailsAdmin::Engine => '/manager-admin', as: 'rails_admin'


  # mount RedactorRails::Engine => '/redactor_rails'
  mount Sidekiq::Web, at: '/sidekiq-monitor'
  # mount UserImpersonate::Engine => "/impersonate", as: "impersonate_engine"
  get "/404", :to => "errors#not_found", as: :error_404
  get "/422", :to => "errors#unacceptable", as: :error_422
  get "/500", :to => "errors#internal_error", as: :error_500

  # config/routes.rb
  get 'switch_user' => 'switch_user#set_current_user'



  # Manager
  namespace :manager do
    get '/', to: 'users#associados', as: 'dashboard'

    resources :pages
    get '/users/clients', to: 'users#clients', as: :user_clients
    get '/users/associados', to: 'users#associados', as: :user_associados
    get '/users/prospection', to: 'users#prospection', as: :user_prospection
    resources :users
    resources :banners
    resources :banner_types
    resources :cupoms
    resources :themed_campaigns
    resources :orders
    resources :bills
    match "/change_password/:id" => "users#change_password", as: :change_password, via: :all

    namespace :ad do
      resources :departments
      resources :categories
      resources :brands
      resources :sub_categories
      resources :products
    end

    namespace :blog do
      resources :posts
      resources :authors
    end

    namespace :sms do
      resources :buys
      resources :campaigns
      resources :reports
      match 'contacts-import', to: 'contacts#import', as: :contacts_import, via: [:get, :post]
    end
  end



  namespace :api, defaults: {format: :json} do
    get 'departments', to: 'departments#index', as: :departments
    resources :products
    devise_scope :user do
      resource :session, only: [:create, :destroy]
    end
  end


  scope 'minha-conta' do

    get '/' => 'site/usuarios#resumo', as: :site_minha_conta
    get '/anuncios' => 'site/usuarios#anuncios', as: :site_anuncios

    # Rotas temporárias
    match "/usuarios/:action" => "site/usuarios#:action", as: :site_usuarios, via: :all
    match "/produto/:action" => "site/produto#:action", as: :site_produtos, via: :all
    match "/download-cupons/:id" => "site/produto#download_cupons", as: :site_download_cupons, via: :all
    match "/atrair/:action" => "site/atrair#:action", as: :site_atrair, via: :all
    match "/analisar/:action" => "site/analisar#:action", as: :site_analisar, via: :all

    get 'customers-group-count', to: 'customers#count', as: :customers_count
    get 'customers-xls', to: 'customers#export_excel', as: :customers_xls

    namespace :sms do
      resources :campaigns, path: 'campanhas'
      resources :buys, path: 'contratar'
      get 'index', as: :index
      put 'sms-update-user', to: 'buys#update_user', as: :update_user
      match 'aniversario', to: 'campaigns#birthday', as: :birthday, via: [:get, :put]
    end
    resources :groups, path: 'grupos'
    resources :customers, path: 'clientes'

    # Campanhas promocionais
    namespace :offers, path: 'ofertas' do
      resources :campaigns, path: 'campanhas'
    end

  end


  # Rotas Institucionais
  get "/sobre" => "site/page#sobre", as: :page_sobre
  get "/atendimento" => "site/page#atendimento", as: :page_atendimento
  get "/como-anunciar" => "site/page#como_anunciar", as: :page_como_anunciar
  get "/politica-de-privacidade" => "site/page#politica", as: :page_politica
  get "/termos-e-condicoes-de-uso" => "site/page#termos", as: :page_termos
  get "/produtos-e-servicos-ilegais" => "site/page#ilegais", as: :page_ilegais
  get "/acesso" => "site/page#acesso", as: :page_acesso
  get "/planos" => "site/page#planos", as: :page_planos
  match "/altera_plano" => "site/page#altera_plano", as: :page_altera_plano, via: :all
  get "/downloads" => "site/page#downloads", as: :page_downloads
  get "/links" => "site/page#links", as: :page_links
  get "/servicos" => "site/page#servicos", as: :page_servicos
  get "/spc/:cidade" => "site/page#spc", as: :page_spc



  # Blog
  # get '/post/:id', to: 'site/blog#show', as: :blog_post
  # get '/blog/:id', to: 'site/blog#index', as: :blog_posts

  # /blog/
  get '/blog', to: 'site/blog#authors', as: :blog
  # /blog/o-nome-do-blog
  get '/blog/:slug_blog', to: 'site/blog#index', as: :blog_author
  # /blog/conteudo/o-titulo-do-post
  get '/blog/conteudo/:slug_post', to: 'site/blog#show', as: :blog_post



  get "/busca" => "site/products#search", as: :site_search
  match "/send-interest" => "site/products#send_interest", as: :send_interest, via: :all
  get "/show-user-info" => "site/products#show_user_info", as: :show_user_info
  get "/produto-nao-encontrado" => "site/products#not_found", as: :product_not_found

  # enviar info do usuário
  get "/show-user-phone/:user_id/(:product_id)" => "site/products#show_user_phone", as: :show_user_phone, format: :json
  # post "/send-track"
  # psot ""

  get "sitemap" => "site/page#sitemap"


  get "/u/:user", to: redirect {|params, req|  "http://#{params[:user]}.#{req.host_with_port}" }#, :status => :moved_permanently

  # Contratação de plano
  match "/contratar" => "site/contratar#planos", as: :contratar_planos, via: :all
  match "/contratar-banners" => "site/contratar#banners", as: :contratar_banners, via: :all
  match "/contratar-dados" => "site/contratar#dados", as: :contratar_dados, via: :all


  resource :inbox, controller: 'inbox' , only: [:show,:create]



  # Rota de Departamentos com subdominio
  constraints DepartmentsConstraint do
    get '/', to: redirect {|params, req| "#{domain(req)}/#{req.subdomain}"}
    get "/:category", to: "site/products#index"
    # get "/servicos", to: "site/products#services", as: :services
    # get "/servico/:category/:product", to: "site/products#show", as: :service
  end

  # Rota para página temática
  constraints ThemedCampaignsConstraint  do
    get "/", to: "site/themed_campaigns#index", as: :themed_campaign
    post "/participar", to: "site/themed_campaigns#create", as: :themed_campaign_create
    get "/participar", to: "site/themed_campaigns#new", as: :themed_campaign_new
  end

  # Rota para lista de produtos do usuário
  constraints UsersConstraint  do
    get "/", to: "site/usuarios#produtos", as: :user_produtos
    get "/:category/:product", to: redirect {|params, req|  "#{domain(req)}/#{req.subdomain}/anuncio/#{params[:category]}/#{params[:product]}" }
  end

  root to: "site/home#index"



  # Ofertas
  get '/ofertas', to: "site/products#offers", as: :ofertas
  get '/cupons', to: "site/products#cupoms", as: :cupons



  # Rota de Departamentos com path
  scope ":department" do
    get '/(:servicos)', to: "site/products#index", as: :department
    get "/categoria/:category/(:servicos)", to: "site/products#index", as: :category
    get "/anuncio/:category/:product", to: "site/products#show", as: :ad
  end




  # get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/controllers/api/products_controller.rb
class Api::ProductsController < Api::BaseController

  def index
    render json: Manager::Ad::Product.all
  end

  def show
    render json: Manager::Ad::Product.find(params[:id])
  end
end

app/controllers/manager/ad/products_controller.rb
# encoding: utf-8
class Manager::Ad::ProductsController < Manager::ManagerController
  inherit_resources

  def index
    unless params[:search]
      @products = Manager::Ad::Product.includes(:category, :user, :department).order(id: :desc).page(params[:page])
    else
      @products = Manager::Ad::Product.where('LOWER(name) like (?)', "%#{params[:search].downcase}%").includes(:category, :user, :department).page(params[:page])
    end
  end



  def new
    @product = Manager::Ad::Product.new(price: 0.0, offer_price: 0.0)
  end



  def edit
    @product = Manager::Ad::Product.find(params[:id])

    if params[:brand_id]
      @product.brand_id = params[:brand_id]
    end
  end



  def create
    @product = Manager::Ad::Product.new(permitted_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to manager_ad_products_path, notice: 'Seu anúncio foi cadastrado com sucesso.'
    else
      render action: 'new'
    end
  end




  def update
    @product = Manager::Ad::Product.find(params[:id])
    if @product.update(permitted_params)
      Rails.cache.clear
      redirect_to manager_ad_products_path, notice: 'Seu anúncio foi atualizado!'
    else
      render action: 'edit'
    end
  end




  def permitted_params
    params.require(:manager_ad_product).permit(
      :name,
      :department_id,
      :category_id,
      :image1,
      :image2,
      :image3,
      :image4,
      :image1_cache,
      :image2_cache,
      :image3_cache,
      :image4_cache,
      :remove_image1,
      :remove_image2,
      :remove_image3,
      :remove_image4,
      :code,
      :price,
      :offer_price,
      :on_request,
      :is_old,
      :description,
      :payment_description,
      :views_count,
      :sub_category_id,
      :is_service,
      :brand_id,
      :script
    )
  end
end

app/controllers/site/analisar_controller.rb
class Site::AnalisarController < ApplicationController
  before_action :verify_pj

  # Lista de campanhas do clictem
  def publico_alvo
    @user = current_user

    if params[:filter]
      @date1 = Date.parse(params[:filter][:date1])
    else
      @date1 = Date.today - 30.days
    end

    if params[:filter]
      @date2 = Date.parse(params[:filter][:date2])
    else
      @date2 = Date.today
    end

    # raise

    @ads = Visit.ads_most_views(@user, @date1, @date2)

  end




end

app/controllers/site/atrair_controller.rb
class Site::AtrairController < ApplicationController
  before_action :verify_pj

  # Lista de campanhas do clictem
  def campanhas
    @campaigns = Manager::Ad::ThemedCampaign.where(active: true, hidden: false)
          .where('date_end >= ?', Date.today)
    @selecteds = current_user.themed_campaigns.pluck(:id)
  end



  # Tela de seleção produtos nas campanhas clictem
  def anuncios
    @campaign = Manager::Ad::ThemedCampaign.find_by_subdomain(params[:campanha])
    if (!current_user.themed_campaigns.include?(@campaign))
        redirect_to site_atrair_path(:confirmar, campanha: @campaign.subdomain)
    else
      @selecteds = @campaign.campaigns.where(user_id: current_user.id).pluck(:product_id)
      @products = current_user.products.published
    end

  end

  def confirmar
    @campaign = Manager::Ad::ThemedCampaign.find_by_subdomain(params[:campanha])
  end

  def concordar
    campaign = Manager::Ad::ThemedCampaign.find_by_subdomain(params[:campanha])
    current_user.themed_campaigns << campaign
    current_user.save
    redirect_to site_atrair_path(:anuncios, campanha: campaign.subdomain)
  end



  # Adicionar anúncios a campanha
  def add_ad_clictem
    @product_id = params[:product]

    campaign = Manager::Ad::ThemedCampaign.find_by_subdomain(params[:campaign])
    campaign.toggle_product_campaign(@product_id)
  end



end

app/controllers/site/blog_controller.rb
class Site::BlogController < ApplicationController

  def authors
    @authors = Blog::Author.all.order('RANDOM()')
  end

  # Lista de posts de um blogueiro
  def index
    @author = Blog::Author.find_by_slug(params[:slug_blog])

    if @author
      @posts = @author.posts.page(params[:page])
      hlp_site_breadcrumb_add("Clictem Blog", blog_path)

      @page_title = @author.title
      @page_description = @author.bio_strip

      @page_og = {
        title: @page_title,
        description:  @page_description,
        type: 'website',
        url: blog_author_url(@author.slug, subdomain: false),
        image: "#{@author.image_url}"
      }

    else
      redirect_to '/404'
    end
  end

  # Postagem
  def show
    @post = Blog::Post.find_by_slug(params[:slug_post])
    if @post
      @department = @post.department
      hlp_site_breadcrumb_add(@post.author.title, blog_author_path(@post.author.slug))

      @page_title = @post.title
      @page_description = @post.text_strip[0..200]

      @page_og = {
        title: @post.title,
        description:  @page_description,
        type: 'website',
        url: blog_post_url(@post.slug, subdomain: false),
        image: "#{@post.image_fb_url}"
      }

      # Buscar produtos relacionados
      # @rel_prods = @department.products.published.includes([:category, user: [:city]]).order('RANDOM()').limit(3)

      @rel_posts = Blog::Post.where(author: @post.author).where.not(id: @post.id).order('RANDOM()').limit(3)

    else
      redirect_to '/404'
    end
  end

end

app/controllers/site/brands_controller.rb
class Site::BrandsController < ApplicationController

  def index
    deparment = Manager::Ad::Department.find(params[:department])
    brands = deparment.brands.order(:name).uniq
    render json: brands
  end


end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController

  def index
  	# TODO Código inserido de forma fixa. Lembrar de tirar
  	user = User.find_by_subdomain('natal')

    # Departamentos mais visualizados nos últimos 7 dias
    @deps = Manager::Ad::Department.unscoped.order('RANDOM()')

    @campaigns = Manager::Ad::ThemedCampaign.where('date_start <= :today and date_end >= :today', today: Date.today).where(active: true)

    # Empresas parceiras
    departamento = Manager::Ad::Department.where(is_home: true).first
    @clients = []
    if departamento != nil
      @clients = departamento.users_premium.where(active: true) 
    end
  end



  def home
    render "site/home/home", layout: false
  end

end

app/helpers/manager/ad/products_helper.rb
module Manager::Ad::ProductsHelper
end

app/helpers/site/account_helper.rb
module Site::AccountHelper
  def hlp_account_is_kind(is_kind)
    'hide' if !is_kind
  end
end

app/helpers/site/active_helper.rb
module Site::ActiveHelper
  def hlp_active_menu(path)
    'active' if request.url == path
  end
end

app/helpers/site/breadcrumb_helper.rb
module Site::BreadcrumbHelper
  # Adiciona as páginas ao breadcrumb. Não é necessário adicionar a home
  def hlp_site_breadcrumb_add(title, url)
    unless @bc_pages
      @bc_pages = []
    end

    @bc_pages << { :title => title, :url => url }
  end

  # Renderiza o breadcrumb. Passar o título da página atual como parâmetro
  def hlp_site_breadcrumb_render(active)
    content_tag(:div, class: 'row') do
      content_tag(:div, class: 'breadcrumbDiv col-md-12') do
        content_tag(:ul, class: 'breadcrumb', :'xmlns:v'=>"http://rdf.data-vocabulary.org/#") do

          concat(content_tag(:li, typeof:"v:Breadcrumb") do # Home
            concat(content_tag(:span, 'Você está em: &nbsp;'.html_safe, class: 'breadcrumb-text color1'))
            if @user and @user.plan != 'free'
              concat(content_tag(:a, @user.name, href: user_produtos_url(subdomain: @user.subdomain), title: 'Página do anunciante', rel:'v:url', property:'v:title', class: 'color2'))
            else
              concat(content_tag(:a, 'Página Inicial', href: root_url(subdomain: false), title: 'Página Inicial', rel:'v:url', property:'v:title', class: 'color2'))
            end
          end)

          if @bc_pages
            @bc_pages.each do |page|
              concat(content_tag(:li, typeof:"v:Breadcrumb") do
                concat(content_tag(:a, page[:title], href: page[:url], title: page[:title], rel:'v:url', property:'v:title', class: 'color2'))
              end)
            end
          end

          concat(content_tag(:li, active, class: 'active color3')) # Texto da página ativa
        end
      end
    end
  end
end

app/views/site/products/_advertiser.html.erb
<% if advertiser_counter == 4 and @department != nil %>
    <%= hlp_banner_page('Banner 5', @department.id) %>
<% end %>

<% cache [advertiser] do %>
    <% if !advertiser.logo? %>
        <div class="advertiser-item free-plan col-md-12">
            <div class="row">
                <h3 class='col-md-8'>
                    <a href="<%= user_produtos_url(subdomain: advertiser.subdomain) %>" class="color2"><%= advertiser.name %></a>
                </h3>
                <div class="col-md-4 info">
                    <% if advertiser.city %>
                        <%= advertiser.city.name %> - <%= advertiser.state.symbol.upcase %> <br>
                    <% end %>
                    <%= link_to user_produtos_url(subdomain: advertiser.subdomain), class: 'btn-link color3' do %>
                    <strong>MAIS INFORMAÇÕES <i class="fa fa-plus-circle"></i></strong>
                <% end %>
                </div>
            </div>
        </div>
    <% else %>
        <div class="advertiser-item col-md-12">
            <div class="logo">
                <%= link_to user_produtos_url(subdomain: advertiser.subdomain) do %>
                  <img src="<%= image_path(advertiser.logo_url(:thumb)) %>" alt="<%= advertiser.name %>" class="img-responsive">
                <% end %>
            </div>

            <div class="info">
                <h3>
                    <a href="<%= user_produtos_url(subdomain: advertiser.subdomain) %>" class="color2"><%= advertiser.name %></a>
                </h3>
                <%= advertiser.city.name %> - <%= advertiser.state.symbol.upcase %> <br>
                <%= link_to user_produtos_url(subdomain: advertiser.subdomain), class: 'btn-link color3' do %>
                <strong>MAIS INFORMAÇÕES <i class="fa fa-plus-circle"></i></strong>
            <% end %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/site/products/_cupom_actions.html.erb
<% if @product.has_cupom? %>
    <iframe name="printCupom" frameborder="0" width="450" height="330" class="hide"></iframe>

    <% if user_signed_in? %> <!-- USUÁRIO LOGADO -->

        <% cupom = current_user.my_cupoms.where(product_id: @product.id) %>
        <% if cupom.present? %>
            <%= link_to site_usuarios_url(:send_cupom, subdomain: false, code: cupom.first.code), remote: true, class: 'btn btn-success', data: { disable_with: 'AGUARDE! ESTAMOS ENVIANDO O E-MAIL' } do %>
                <i class="fa fa-ticket"></i> RE-ENVIAR CUPOM PARA E-MAIL
            <% end %>

            <%= link_to site_usuarios_url(:print_cupom, subdomain: false, code: cupom.first.code), target: 'printCupom', class: 'btn btn-default print-cupom' do %>
                <i class="fa fa-print"></i> IMPRIMIR CUPOM
            <% end %>

        <% else %>

            <% if @product.has_cupom_limit? %>
                <% if @product.cupom_generated >= @product.cupom_limit %>
                    <div class="alert alert-info">
                        <i class="fa fa-ticket"></i> <strong>CUPONS ESGOTADOS!</strong> <br>
                        Chegamos ao limite de <strong><%= @product.cupom_limit %></strong> cupons de desconto gerados. Curta nossa página no Facebook e acompanhe as melhores ofertas da região. <br>

                        <br>
                        <div class="fb-like-box" data-href="https://www.facebook.com/<%= @current_org.facebook %>" data-width="380" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
                    </div>
                <% else %>                    <%= link_to site_usuarios_url(:gen_cupom, subdomain: 'www', product: @product.id), remote: true, class: 'btn btn-success gen-cupom', data: { disable_with: 'AGUARDE! ESTAMOS GERANDO SEU CUPOM' } do %>
                        <i class="fa fa-ticket"></i> EMITIR CUPOM DE DESCONTO
                    <% end %>
                    <div><small>Oferta limitada a <strong><%= @product.cupom_limit %></strong> cupons gerados.</small></div>
                <% end %>
            <% else %>
                <%= link_to site_usuarios_url(:gen_cupom, subdomain: 'www', product: @product.id), remote: true, class: 'btn btn-success gen-cupom', data: { disable_with: 'AGUARDE! ESTAMOS GERANDO SEU CUPOM' } do %>
                    <i class="fa fa-ticket"></i> EMITIR CUPOM DE DESCONTO
                <% end %>
            <% end %>


        <% end %>

    <% else %> <!-- USUÁRIO PÚBLICO -->

        <% if @product.has_cupom_limit? %>
            <% if @product.cupom_generated >= @product.cupom_limit %>
                <div class="alert alert-info">
                    <i class="fa fa-ticket"></i> <strong>CUPONS ESGOTADOS!</strong> <br>
                    Chegamos ao limite de <strong><%= @product.cupom_limit %></strong> cupons de desconto gerados. Curta nossa página no Facebook e acompanhe as melhores ofertas da região. <br>

                    <br>
                    <div class="fb-like-box" data-href="https://www.facebook.com/<%= @current_org.facebook %>" data-width="380" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
                </div>
            <% else %>
                <%= link_to page_acesso_path(prodCP: @product.slug), class: 'btn btn-success' do %>
                    <i class="fa fa-ticket"></i> EMITIR CUPOM DE DESCONTO
                <% end %>
                <br><small>Oferta limitada a <strong><%= @product.cupom_limit %></strong> cupons gerados.</small>
            <% end %>
        <% else %>
            <%= link_to page_acesso_path(prodCP: @product.slug), class: 'btn btn-success' do %>
                <i class="fa fa-ticket"></i> EMITIR CUPOM DE DESCONTO
            <% end %>
        <% end %>

    <% end %>
<% end %>

app/views/site/products/_prices.html.erb
<% if @product.on_request? or @product.price.to_f == 0 %>
    <div class="product-price">
            <small class="price-sales color1">CONSULTE O PREÇO</small>
    </div>
<% else %>
    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
        <meta itemprop="priceCurrency" content="BRL" />
        <% if @product.offer_valid? %>
            <div class="product-price">
                <span class="price-standard">
                    <small>DE <%= number_to_currency(@product.price.to_f) %></small>
                </span>
                <br />

                <div class="price-sales color1">
                    <small>POR </small>
                    <span itemprop="price" content="<%= @product.offer_price %>"><%= number_to_currency(@product.offer_price.to_f) %></span>
                    <% if @product.percentage_off > 5 %>
                        <span class='product-discount'> (<%= @product.percentage_off %>% <small>DE DESCONTO</small>)</span>
                    <% end %>
                </div>

            </div>
            <time itemprop="priceValidUntil" datetime="<%= l @product.offer_end, format: '%Y-%m-%d' %>"></time>
        <% else %>
            <div class="product-price">

                <span class="price-sales color1" itemprop="price" content="<%= @product.offer_price %>">
                        <% if @product.from_only? %>
                            <small>A partir de </small><br>
                        <% end %>
                    <%= number_to_currency(@product.price.to_f) %>
                </span>
            </div>
        <% end %>
    </div>

    <!-- Cupom de desconto -->
    <div class="row">
        <div class="col-md-12 cupom-actions">
            <%= render 'cupom_actions' %>
        </div>
    </div>
<% end %>

app/views/site/products/cupoms.html.erb
<%= hlp_site_breadcrumb_render("Emita seus cupons") %>

<div class="row">
    <!--left column-->

    <div class="col-lg-3 col-md-3 col-sm-12">
        <div class="row">
            <div class="col-md-12">
                <% if @related.size > 0 %>
                    Destaque

                    <% @related.each do |user| %>
                        <%= link_to user_produtos_url(subdomain: user.subdomain) do %>
                            <%= image_tag(user.logo_url(:highlight), class: 'img-responsive') %>
                            <br>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>

        <div class="panel-group" id="accordionNo">

            <!--Category-->
            <% @departments.each do |department| %>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse"  href="#collapseCategory" class="collapseWill">
                                <span class="pull-left"> <i class="fa fa-caret-right"></i></span>
                                <%= department.name %>
                            </a>
                        </h4>
                    </div>

                    <div id="collapseCategory" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked tree">
                                <% department.categories.where(id: @categories).each do |cat| %>
                                <li class="<%= hlp_active_menu(category_url(department.slug, cat.slug,subdomain: false)) %> dropdown-tree open-tree">
                                    <a href="<%= cupons_url(category: cat.id, subdomain: false) %>" class="dropdown-tree-a">
                                        <% if cat.products.size > 0 %>
                                            <span class="badge pull-right">
                                                <%= @categories.grep(cat.id).size %>
                                            </span>
                                        <% end %>

                                        <i class="fa fa-chevron-right"></i> <%= cat.name %>
                                    </a>
                                </li>
                                <% end %>
                            </ul>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>

    <!--right column-->
    <div class="col-lg-9 col-md-9 col-sm-12">

        <div class="w100 clearfix category-top">
            <h2> Emita seus cupons abaixo </h2>
        </div><!--/.category-top-->

        <!-- Lista de produtos -->
        <div class="w100 productFilter clearfix">
            <% if @products.class != Array %>
                <p class="pull-left"> Foram encontrados <strong><%= @products.total_count %></strong> anúncios </p>
            <% end %>
            <div class="pull-right">
                <div class="change-view pull-right">
                <a href="#" title="Grade" class="grid-view"> <i class="fa fa-th-large"></i> </a>
                <a href="#" title="Lista" class="list-view "><i class="fa fa-th-list"></i></a> </div>
            </div>
        </div> <!--/.productFilter-->

        <div class="row categoryProduct xsResponse clearfix">
            <%= render partial: 'product', collection: @products, locals: { item_class: 'col-md-4' } %>
        </div> <!--/.categoryProduct || product content end-->



        <div class="w100 categoryFooter">
            <div class="clearfix">
                <div class="col-md-12">
                    <% if @products.class != Array %>
                        <div class="hide"><%= paginate @products %></div>
                    <% end %>
                </div>
            </div>
            <div class="pull-right pull-right col-sm-4 col-xs-12 no-padding text-right text-left-xs">
                <!-- <p>Showing 1–450 of 12 results</p> -->
            </div>
        </div> <!--/.categoryFooter-->
    </div><!--/right column end-->
</div><!-- /.row  -->