config/routes.rb
require 'sidekiq/web'
require 'users_constraint'
require 'departments_constraint'
require 'themed_campaigns_constraint'

# Sobrescrevendo a classe para poder reutilizar o método .domain
class ActionDispatch::Routing::Mapper
  def domain(request)
    request.protocol + request.domain + (request.port.nil? ? '' : ":#{request.port}")
  end

  def current_domain(request)
    request.domain + (request.port.nil? ? '' : ":#{request.port}")
  end
end

Rails.application.routes.draw do

  # devise_for :admins

  if Rails.env.production?
    # Redirecionar .com para .com.br
    constraints(host: "clictem.com") do
      match "/(*path)" => redirect {|params, req|

        if req.subdomains(0).first.present? and
           req.subdomains(0).first != "www" and
           req.subdomains(0).first != "clictem" and
           req.subdomains(0).first != "lvh"
          subdomain = "#{req.subdomains(0).first}."
        else
          subdomain = ''
        end

        "http://#{subdomain}clictem.com.br/#{params[:path]}"},  via: [:get, :post]
    end
  end


  # Redirecionar www para non-www somente se for algum subdominio
  constraints(host: /www.(?!cdlxanxere|cdlxaxim|clictem|xanxeretem)/i) do
    match "/(*path)" => redirect {|params, req|

      if req.subdomains(0).first.present? and
         req.subdomains(0).first != "www" and
         DOMAINS.include?(req.subdomains(0).first) == false
        subdomain = "#{req.subdomains(0).first}."

      elsif req.subdomains(0).first == 'www' and
            DOMAINS.include?(req.subdomains(0)[1].first) == false
        subdomain = "#{req.subdomains(0)[1]}."

      else
        subdomain = ''
      end

      "http://#{subdomain}#{current_domain(req)}/#{params[:path]}"},  via: [:get, :post]
  end


  namespace :site do
    get 'visits/new'
    get 'brands', to: 'brands#index', as: :brands
    resources :comments
  end



  devise_for :users, :path => '',
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },
    :path_names => {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'cadastre-se',
      confirmation: "confirme-seu-email",
      password: "alterar-senha"
    }




  # mount MailPreview => 'mail_view' if Rails.env.development?
  # mount RailsAdmin::Engine => '/manager-admin', as: 'rails_admin'


  # mount RedactorRails::Engine => '/redactor_rails'
  mount Sidekiq::Web, at: '/sidekiq-monitor'
  # mount UserImpersonate::Engine => "/impersonate", as: "impersonate_engine"
  get "/404", :to => "errors#not_found", as: :error_404
  get "/422", :to => "errors#unacceptable", as: :error_422
  get "/500", :to => "errors#internal_error", as: :error_500

  # config/routes.rb
  get 'switch_user' => 'switch_user#set_current_user'



  # Manager
  namespace :manager do
    get '/', to: 'users#associados', as: 'dashboard'

    resources :pages
    get '/users/clients', to: 'users#clients', as: :user_clients
    get '/users/associados', to: 'users#associados', as: :user_associados
    get '/users/prospection', to: 'users#prospection', as: :user_prospection
    resources :users
    resources :banners
    resources :banner_types
    resources :cupoms
    resources :themed_campaigns
    resources :orders
    resources :bills
    match "/change_password/:id" => "users#change_password", as: :change_password, via: :all

    namespace :ad do
      resources :departments
      resources :categories
      resources :brands
      resources :sub_categories
      resources :products
    end

    namespace :blog do
      resources :posts
      resources :authors
    end

    namespace :sms do
      resources :buys
      resources :campaigns
      resources :reports
      match 'contacts-import', to: 'contacts#import', as: :contacts_import, via: [:get, :post]
    end
  end



  namespace :api, defaults: {format: :json} do
    get 'departments', to: 'departments#index', as: :departments
    resources :products
    devise_scope :user do
      resource :session, only: [:create, :destroy]
    end
  end


  scope 'minha-conta' do

    get '/' => 'site/usuarios#resumo', as: :site_minha_conta
    get '/anuncios' => 'site/usuarios#anuncios', as: :site_anuncios

    # Rotas temporárias
    match "/usuarios/:action" => "site/usuarios#:action", as: :site_usuarios, via: :all
    match "/produto/:action" => "site/produto#:action", as: :site_produtos, via: :all
    match "/download-cupons/:id" => "site/produto#download_cupons", as: :site_download_cupons, via: :all
    match "/atrair/:action" => "site/atrair#:action", as: :site_atrair, via: :all
    match "/analisar/:action" => "site/analisar#:action", as: :site_analisar, via: :all

    get 'customers-group-count', to: 'customers#count', as: :customers_count
    get 'customers-xls', to: 'customers#export_excel', as: :customers_xls

    namespace :sms do
      resources :campaigns, path: 'campanhas'
      resources :buys, path: 'contratar'
      get 'index', as: :index
      put 'sms-update-user', to: 'buys#update_user', as: :update_user
      match 'aniversario', to: 'campaigns#birthday', as: :birthday, via: [:get, :put]
    end
    resources :groups, path: 'grupos'
    resources :customers, path: 'clientes'

    # Campanhas promocionais
    namespace :offers, path: 'ofertas' do
      resources :campaigns, path: 'campanhas'
    end

  end


  # Rotas Institucionais
  get "/sobre" => "site/page#sobre", as: :page_sobre
  get "/atendimento" => "site/page#atendimento", as: :page_atendimento
  get "/como-anunciar" => "site/page#como_anunciar", as: :page_como_anunciar
  get "/politica-de-privacidade" => "site/page#politica", as: :page_politica
  get "/termos-e-condicoes-de-uso" => "site/page#termos", as: :page_termos
  get "/produtos-e-servicos-ilegais" => "site/page#ilegais", as: :page_ilegais
  get "/acesso" => "site/page#acesso", as: :page_acesso
  get "/planos" => "site/page#planos", as: :page_planos
  match "/altera_plano" => "site/page#altera_plano", as: :page_altera_plano, via: :all
  get "/downloads" => "site/page#downloads", as: :page_downloads
  get "/links" => "site/page#links", as: :page_links
  get "/servicos" => "site/page#servicos", as: :page_servicos
  get "/spc/:cidade" => "site/page#spc", as: :page_spc



  # Blog
  # get '/post/:id', to: 'site/blog#show', as: :blog_post
  # get '/blog/:id', to: 'site/blog#index', as: :blog_posts

  # /blog/
  get '/blog', to: 'site/blog#authors', as: :blog
  # /blog/o-nome-do-blog
  get '/blog/:slug_blog', to: 'site/blog#index', as: :blog_author
  # /blog/conteudo/o-titulo-do-post
  get '/blog/conteudo/:slug_post', to: 'site/blog#show', as: :blog_post



  get "/busca" => "site/products#search", as: :site_search
  match "/send-interest" => "site/products#send_interest", as: :send_interest, via: :all
  get "/show-user-info" => "site/products#show_user_info", as: :show_user_info
  get "/produto-nao-encontrado" => "site/products#not_found", as: :product_not_found

  # enviar info do usuário
  get "/show-user-phone/:user_id/(:product_id)" => "site/products#show_user_phone", as: :show_user_phone, format: :json
  # post "/send-track"
  # psot ""

  get "sitemap" => "site/page#sitemap"


  get "/u/:user", to: redirect {|params, req|  "http://#{params[:user]}.#{req.host_with_port}" }#, :status => :moved_permanently

  # Contratação de plano
  match "/contratar" => "site/contratar#planos", as: :contratar_planos, via: :all
  match "/contratar-banners" => "site/contratar#banners", as: :contratar_banners, via: :all
  match "/contratar-dados" => "site/contratar#dados", as: :contratar_dados, via: :all


  resource :inbox, controller: 'inbox' , only: [:show,:create]



  # Rota de Departamentos com subdominio
  constraints DepartmentsConstraint do
    get '/', to: redirect {|params, req| "#{domain(req)}/#{req.subdomain}"}
    get "/:category", to: "site/products#index"
    # get "/servicos", to: "site/products#services", as: :services
    # get "/servico/:category/:product", to: "site/products#show", as: :service
  end

  # Rota para página temática
  constraints ThemedCampaignsConstraint  do
    get "/", to: "site/themed_campaigns#index", as: :themed_campaign
    post "/participar", to: "site/themed_campaigns#create", as: :themed_campaign_create
    get "/participar", to: "site/themed_campaigns#new", as: :themed_campaign_new
  end

  # Rota para lista de produtos do usuário
  constraints UsersConstraint  do
    get "/", to: "site/usuarios#produtos", as: :user_produtos
    get "/:category/:product", to: redirect {|params, req|  "#{domain(req)}/#{req.subdomain}/anuncio/#{params[:category]}/#{params[:product]}" }
  end

  root to: "site/home#index"



  # Ofertas
  get '/ofertas', to: "site/products#offers", as: :ofertas
  get '/cupons', to: "site/products#cupoms", as: :cupons



  # Rota de Departamentos com path
  scope ":department" do
    get '/(:servicos)', to: "site/products#index", as: :department
    get "/categoria/:category/(:servicos)", to: "site/products#index", as: :category
    get "/anuncio/:category/:product", to: "site/products#show", as: :ad
  end




  # get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/controllers/site/analisar_controller.rb
class Site::AnalisarController < ApplicationController
  before_action :verify_pj

  # Lista de campanhas do clictem
  def publico_alvo
    @user = current_user

    if params[:filter]
      @date1 = Date.parse(params[:filter][:date1])
    else
      @date1 = Date.today - 30.days
    end

    if params[:filter]
      @date2 = Date.parse(params[:filter][:date2])
    else
      @date2 = Date.today
    end

    # raise

    @ads = Visit.ads_most_views(@user, @date1, @date2)

  end




end

app/controllers/site/atrair_controller.rb
class Site::AtrairController < ApplicationController
  before_action :verify_pj

  # Lista de campanhas do clictem
  def campanhas
    @campaigns = Manager::Ad::ThemedCampaign.where(active: true, hidden: false)
          .where('date_end >= ?', Date.today)
    @selecteds = current_user.themed_campaigns.pluck(:id)
  end



  # Tela de seleção produtos nas campanhas clictem
  def anuncios
    @campaign = Manager::Ad::ThemedCampaign.find_by_subdomain(params[:campanha])
    if (!current_user.themed_campaigns.include?(@campaign))
        redirect_to site_atrair_path(:confirmar, campanha: @campaign.subdomain)
    else
      @selecteds = @campaign.campaigns.where(user_id: current_user.id).pluck(:product_id)
      @products = current_user.products.published
    end

  end

  def confirmar
    @campaign = Manager::Ad::ThemedCampaign.find_by_subdomain(params[:campanha])
  end

  def concordar
    campaign = Manager::Ad::ThemedCampaign.find_by_subdomain(params[:campanha])
    current_user.themed_campaigns << campaign
    current_user.save
    redirect_to site_atrair_path(:anuncios, campanha: campaign.subdomain)
  end



  # Adicionar anúncios a campanha
  def add_ad_clictem
    @product_id = params[:product]

    campaign = Manager::Ad::ThemedCampaign.find_by_subdomain(params[:campaign])
    campaign.toggle_product_campaign(@product_id)
  end



end

app/controllers/site/blog_controller.rb
class Site::BlogController < ApplicationController

  def authors
    @authors = Blog::Author.all.order('RANDOM()')
  end

  # Lista de posts de um blogueiro
  def index
    @author = Blog::Author.find_by_slug(params[:slug_blog])

    if @author
      @posts = @author.posts.page(params[:page])
      hlp_site_breadcrumb_add("Clictem Blog", blog_path)

      @page_title = @author.title
      @page_description = @author.bio_strip

      @page_og = {
        title: @page_title,
        description:  @page_description,
        type: 'website',
        url: blog_author_url(@author.slug, subdomain: false),
        image: "#{@author.image_url}"
      }

    else
      redirect_to '/404'
    end
  end

  # Postagem
  def show
    @post = Blog::Post.find_by_slug(params[:slug_post])
    if @post
      @department = @post.department
      hlp_site_breadcrumb_add(@post.author.title, blog_author_path(@post.author.slug))

      @page_title = @post.title
      @page_description = @post.text_strip[0..200]

      @page_og = {
        title: @post.title,
        description:  @page_description,
        type: 'website',
        url: blog_post_url(@post.slug, subdomain: false),
        image: "#{@post.image_fb_url}"
      }

      # Buscar produtos relacionados
      # @rel_prods = @department.products.published.includes([:category, user: [:city]]).order('RANDOM()').limit(3)

      @rel_posts = Blog::Post.where(author: @post.author).where.not(id: @post.id).order('RANDOM()').limit(3)

    else
      redirect_to '/404'
    end
  end

end

app/controllers/site/brands_controller.rb
class Site::BrandsController < ApplicationController

  def index
    deparment = Manager::Ad::Department.find(params[:department])
    brands = deparment.brands.order(:name).uniq
    render json: brands
  end


end

app/controllers/site/comments_controller.rb
class Site::CommentsController < ApplicationController
	skip_before_filter :verify_authenticity_token, :only => [:index, :new, :create]

	def index
		@product  = Manager::Ad::Product.find(params[:product_id])
		@comments = @product.comments.where(question_id: nil, deleted: false).order('id DESC')
	end



	def new
		@comment = Comment.new(product_id: params[:product_id], question_id: params[:question_id], seller_id: params[:seller_id])
	end



	def create
		@comment = Comment.new(interest_params)
		@comment.save

		if @comment.is_anwser?
				email = Mails::ProductMailer.anwser(@comment).deliver
		else
				email = Mails::ProductMailer.comment(@comment).deliver
				@comment.seller.notifications.new.save_email(email)


			Customer.create_lead(@comment.seller, @comment.user.email, {funnel: 1,
            	name: @comment.user.fullname,
            	phone: @comment.user.phone,
            	cellphone: @comment.user.cellphone,
            	genre: @comment.user.genre
            })
		end

	end


	def destroy
		@product = Manager::Ad::Product.find(params[:product_id])
		@user    = @product.user
		if current_user == @user
			@comment = Comment.find(params[:id])
			if @comment.deleted == false
				@comment.deleted = true
			else
				@comment.deleted = false
			end
			@comment.save
		end
	end


	private

	def interest_params
	  params.require(:comment).permit!
	end
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController

  def index
  	# TODO Código inserido de forma fixa. Lembrar de tirar
  	user = User.find_by_subdomain('natal')

    # Departamentos mais visualizados nos últimos 7 dias
    @deps = Manager::Ad::Department.unscoped.order('RANDOM()')

    @campaigns = Manager::Ad::ThemedCampaign.where('date_start <= :today and date_end >= :today', today: Date.today).where(active: true)

    # Empresas parceiras
    departamento = Manager::Ad::Department.where(is_home: true).first
    @clients = []
    if departamento != nil
      @clients = departamento.users_premium.where(active: true) 
    end
  end



  def home
    render "site/home/home", layout: false
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/site/account_helper.rb
module Site::AccountHelper
  def hlp_account_is_kind(is_kind)
    'hide' if !is_kind
  end
end

app/helpers/site/active_helper.rb
module Site::ActiveHelper
  def hlp_active_menu(path)
    'active' if request.url == path
  end
end

app/helpers/site/breadcrumb_helper.rb
module Site::BreadcrumbHelper
  # Adiciona as páginas ao breadcrumb. Não é necessário adicionar a home
  def hlp_site_breadcrumb_add(title, url)
    unless @bc_pages
      @bc_pages = []
    end

    @bc_pages << { :title => title, :url => url }
  end

  # Renderiza o breadcrumb. Passar o título da página atual como parâmetro
  def hlp_site_breadcrumb_render(active)
    content_tag(:div, class: 'row') do
      content_tag(:div, class: 'breadcrumbDiv col-md-12') do
        content_tag(:ul, class: 'breadcrumb', :'xmlns:v'=>"http://rdf.data-vocabulary.org/#") do

          concat(content_tag(:li, typeof:"v:Breadcrumb") do # Home
            concat(content_tag(:span, 'Você está em: &nbsp;'.html_safe, class: 'breadcrumb-text color1'))
            if @user and @user.plan != 'free'
              concat(content_tag(:a, @user.name, href: user_produtos_url(subdomain: @user.subdomain), title: 'Página do anunciante', rel:'v:url', property:'v:title', class: 'color2'))
            else
              concat(content_tag(:a, 'Página Inicial', href: root_url(subdomain: false), title: 'Página Inicial', rel:'v:url', property:'v:title', class: 'color2'))
            end
          end)

          if @bc_pages
            @bc_pages.each do |page|
              concat(content_tag(:li, typeof:"v:Breadcrumb") do
                concat(content_tag(:a, page[:title], href: page[:url], title: page[:title], rel:'v:url', property:'v:title', class: 'color2'))
              end)
            end
          end

          concat(content_tag(:li, active, class: 'active color3')) # Texto da página ativa
        end
      end
    end
  end
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
  def hlp_categories_cache(where)
    # max_updated_at = Manager::Ad::Category.maximum(:updated_at).try(:utc).try(:to_s, :number)
    # max_updated_at2 = Manager::Ad::Department.maximum(:updated_at).try(:utc).try(:to_s, :number)
    updated = Time.zone.now.hour
    "#{where}/#{updated}"
  end
end

app/helpers/site/contratar_helper.rb
module Site::ContratarHelper

    def hlp_selected_banner?(id)
        if session[:banners]
            session[:banners].include?(id.to_s)
        else
            false
        end
    end


    def hlp_selected_department?(bannerId, deptId)
       if session[:depts] and session[:depts][bannerId.to_s]
            session[:depts][bannerId.to_s].include?(deptId.to_s)
        else
            false
        end
    end

end

app/views/site/comments/_anwser.html.erb
<div class="col-md-11 col-md-offset-1 anwser<%= anwser.id %>">
	<div class="panel panel-success">
	  <div class="panel-heading">
	  	<strong><%= link_to anwser.user.name, user_produtos_url(subdomain: anwser.user.subdomain) %></strong>
	  	<small class="pull-right"><%= l anwser.created_at, format: :long %></small>
	  </div>

	  <div class="panel-body">
	    <%= anwser.text %>
	  </div>

	  <% if current_user and anwser.product.user_id == current_user.id  %>

		<div class="panel-footer">
	  	  	<%= link_to site_comment_path(anwser.id, product_id: anwser.product_id), class: 'btn btn-danger btn-sm', remote: true, method: :delete, data: { confirm: 'Deseja mesmo excluir esta reposta?' } do %>
	  			<i class="fa fa-trash"></i> Excluir resposta
	  	  	<% end %>
  	  	</div>
	  	  	
	  <% end %>
	</div>
</div>

app/views/site/comments/_comment.html.erb
<div class="clearfix comment<%= comment.id %>">
	<div class="col-md-11">
		<div class="panel <%= comment.deleted ? 'panel-danger' : 'panel-info' %>">
		  <div class="panel-heading">
		  	<% if defined? product %>
		  		<strong><%= product.name %></strong><br />
		  	<% else %>
				<% product = comment.product %>
		  	<% end %>

		  	<strong><%= link_to comment.user.name, user_produtos_url(subdomain: comment.user.subdomain) %></strong>
		  	<small class="pull-right"><%= l comment.created_at, format: :long %></small>
		  </div>

		  <div class="panel-body">
		    <%= comment.text %>
		  </div>

		  <% if current_user and product.user_id == current_user.id  %>

			<div class="panel-footer comment-show<%= comment.id %> <%= comment.deleted ? '' : 'hide'  %>">
	  		  	<%= link_to site_comment_path(comment.id, product_id: comment.product_id), class: 'btn btn-default btn-sm', remote: true, method: :delete do %>
	  				<i class="fa fa-eye"></i> Exibir novamente
	  		  	<% end %>

	  		  	<span class="label label-danger pull-right">Comentário excluído</span>
  		  	</div>

			<div class="panel-footer comment-delete<%= comment.id %> <%= comment.deleted ? 'hide' : ''  %>">
			  	<%= link_to new_site_comment_path(product_id: comment.product_id, question_id: comment.id, seller_id: comment.seller_id), class: 'btn btn-success btn-sm', remote: true do %>
					<i class="fa fa-comments"></i> Responder
			  	<% end %>

		  	  	<%= link_to site_comment_path(comment.id, product_id: comment.product_id), class: 'btn btn-danger btn-sm pull-right', remote: true, method: :delete, data: { confirm: 'Deseja mesmo excluir este comentário?' } do %>
		  			<i class="fa fa-trash"></i> Excluir
		  	  	<% end %>
	  	  	</div>

		  <% end %>
		</div>
	</div>

	<div class="comment-response-<%= comment.id %>"></div>

	<% comment.anwsers.where(deleted: false).each do |anwser| %>
		<%= render '/site/comments/anwser', anwser: anwser %>
	<% end %>
</div>

app/views/site/comments/_form.html.erb
<div class="row">
	<div class="col-md-12">
		<% if user_signed_in? %>
			<%= simple_form_for @comment, url: site_comments_path, remote: true do |f| %>
				<%= f.hidden_field :product_id %>
				<%= f.hidden_field :seller_id %>
				<%= f.hidden_field :user_id, value: current_user.id %>
				<%= f.input :text, label: false, placeholder: 'Deixe aqui seu comentário' %>
				<div class="clearfix">
					<button type='submit' class='btn btn-lg btn-primary pull-right bg1 border1' onclick="exibeAguardando();">
						<span class="aguarde hide"><i class="fa fa-circle-o-notch fa-spin fa-fw"></i> Aguarde</span>
						<span class="comentar"><i class="fa fa-comments-o"></i> Comentar</span>
					</button>
				</div>
			<% end %>
		<% else %>
			<h2 class="block-title-2"><span>Você precisa estar cadastrado para comentar</span></h2>
            <%= link_to page_acesso_url(subdomain: false, prodCM: @comment.product.id), class: 'btn btn-fb btn-block btn-lg' do %>
                <i class="fa fa-comment-o"></i> Comente agora este anúncio
            <% end %>
		<% end %>
	</div>
</div>

app/views/site/comments/_index.html.erb
<div class="row">
	<%= render @comments %>
</div>

app/views/site/comments/_response.html.erb
<div class="clearfix">
	<div class="col-md-10 col-md-offset-2">
		<div class="panel panel-success">
		  <div class="panel-heading">
		  	<strong><%= current_user.name %></strong>
		  </div>

		  <%= simple_form_for @comment, url: site_comments_path, remote: true do |f| %>
			  <div class="panel-body">
			    	<%= f.hidden_field :product_id %>
			    	<%= f.hidden_field :seller_id %>
			    	<%= f.hidden_field :user_id, value: current_user.id %>
			    	<%= f.hidden_field :question_id %>
			    	<%= f.input :text, label: false, placeholder: 'Deixe aqui sua resposta' %>
			  </div>

			  <div class="panel-footer">
			  	<button type='submit' class='btn btn-success btn-sm'><i class="fa fa-comments"></i> Publicar resposta</button>
			  </div>
		  <% end %>

		</div>
	</div>
</div>

app/views/site/comments/create.js.erb
<% if @comment.question %>
	$('.comment-response-<%= @comment.question_id %>').html("<%= j render '/site/comments/anwser', anwser: @comment %>");
<% else %>
	$('.comments-list').prepend("<div class='row'><%= j render '/site/comments/comment', comment: @comment %></div>");
  $('.comments-form').html('<div class="alert alert-info alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Fechar"><span aria-hidden="true">&times;</span></button><strong><i class="glyphicon glyphicon-ok-circle"></i> SUA MENSAGEM FOI ENVIADA!</strong><br />Acabamos de enviar um e-mail para o anunciante. Ele entrará em contato com você o mais breve possível.<br />Muito obrigado por utilizar o sistema <strong><%= @current_org.fullname %></strong>. </div>');
<% end %>

app/views/site/comments/destroy.js.erb
<% if @comment.is_anwser? %>

	$('.anwser<%= @comment.id %>').fadeOut();

<% else %>

	<% if @comment.deleted %>

		$('.comment<%= @comment.id %> .panel:first').addClass('panel-danger');
		$('.comment<%= @comment.id %> .panel:first').removeClass('panel-info');

		$('.comment-show<%= @comment.id %>').removeClass('hide');
		$('.comment-delete<%= @comment.id %>').addClass('hide');

		if($('#visit-data').size() > 0){
			$('.comment<%= @comment.id %>').fadeOut();
		}

	<% else %>

		$('.comment<%= @comment.id %> .panel:first').removeClass('panel-danger');
		$('.comment<%= @comment.id %> .panel:first').addClass('panel-info');

		$('.comment-show<%= @comment.id %>').addClass('hide');
		$('.comment-delete<%= @comment.id %>').removeClass('hide');

	<% end %>

<% end %>
	

app/views/site/comments/index.js.erb
$('.comments-list').html("<%= j render 'index' %>")

app/views/site/comments/new.js.erb
<% if @comment.question %>
	$('.comment-response-<%= @comment.question_id %>').html("<%= j render 'response' %>")
<% else %>
	$('.comments-form').html("<%= j render 'form' %>")
<% end %>